{pkgs, lib, inputs, ...}:

let
  # Personal Info
  name = "Jonathan Reeve";
  email = "jonathan@jonreeve.com";
  githubUsername = "JonathanReeve";
  # Paths
  dots = "/home/jon/Agordoj/dotfiles";
  dokumentoj = "/home/jon/Dokumentoj";
  scripts = "/home/jon/Agordoj/scripts";
  maildir = "/home/jon/Retpoŝto";
  vaultmount = "/home/jon/.private-mount";
  vaultloc = "${dokumentoj}/Personal/.Vault_gocryptfs";
  # Preferences
  font = "Victor Mono";
  backgroundColor = "#243442"; # Blue steel
  foregroundColor = "#deedf9"; # Light blue
  warningColor = "#e23131"; # Reddish
  lockCmd = "${pkgs.swaylock-fancy}/bin/swaylock-fancy -p -t ''";
  brightnessctl = "${pkgs.brightnessctl}/bin/brightnessctl";
  
  # Binary paths
  emacsclient = "/etc/profiles/per-user/jon/bin/emacsclient";
  qutebrowser = "${pkgs.qutebrowser}/bin/qutebrowser";
  matugen = "${pkgs.matugen}/bin/matugen";
  
  # Matugen templates
  ewalTemplate = ''
    {
      "colors": {
        "color0": "{{colors.surface.default.hex}}",
        "color1": "{{colors.error.default.hex}}",
        "color2": "{{colors.primary.default.hex}}",
        "color3": "{{colors.tertiary.default.hex}}",
        "color4": "{{colors.secondary.default.hex}}",
        "color5": "{{colors.primary_fixed.default.hex}}",
        "color6": "{{colors.secondary_fixed.default.hex}}",
        "color7": "{{colors.on_surface.default.hex}}",
        "color8": "{{colors.outline.default.hex}}",
        "color9": "{{colors.error_container.default.hex}}",
        "color10": "{{colors.primary_container.default.hex}}",
        "color11": "{{colors.tertiary_container.default.hex}}",
        "color12": "{{colors.secondary_container.default.hex}}",
        "color13": "{{colors.inverse_primary.default.hex}}",
        "color14": "{{colors.inverse_surface.default.hex}}",
        "color15": "{{colors.surface_bright.default.hex}}"
      },
      "special": {
        "background": "{{colors.surface.default.hex}}",
        "foreground": "{{colors.on_surface.default.hex}}",
        "cursor": "{{colors.primary.default.hex}}"
      }
    }
  '';
  
  qutebrowserTemplate = ''
    # Qutebrowser theming generated by Matugen
    bg = "{{colors.surface.default.hex}}"
    bg_alt = "{{colors.surface_container.default.hex}}"
    bg_focused = "{{colors.primary.default.hex}}"
    fg = "{{colors.on_surface.default.hex}}"
    fg_alt = "{{colors.on_surface_variant.default.hex}}"
    fg_focused = "{{colors.on_primary.default.hex}}"
    accent = "{{colors.tertiary.default.hex}}"
    error = "{{colors.error.default.hex}}"

    # Completion
    c.colors.completion.category.bg = bg_alt
    c.colors.completion.category.fg = fg
    c.colors.completion.category.border.bottom = bg
    c.colors.completion.category.border.top = bg
    c.colors.completion.fg = fg_alt
    c.colors.completion.item.selected.bg = bg_focused
    c.colors.completion.item.selected.border.bottom = bg_focused
    c.colors.completion.item.selected.border.top = bg_focused
    c.colors.completion.item.selected.fg = fg_focused
    c.colors.completion.item.selected.match.fg = accent
    c.colors.completion.match.fg = accent
    c.colors.completion.scrollbar.bg = bg
    c.colors.completion.scrollbar.fg = fg

    # Statusbar
    c.colors.statusbar.normal.bg = bg
    c.colors.statusbar.normal.fg = fg
    c.colors.statusbar.insert.bg = accent
    c.colors.statusbar.insert.fg = fg_focused
    c.colors.statusbar.command.bg = bg
    c.colors.statusbar.command.fg = fg

    # Tabs
    c.colors.tabs.bar.bg = bg
    c.colors.tabs.even.bg = bg
    c.colors.tabs.even.fg = fg
    c.colors.tabs.odd.bg = bg_alt
    c.colors.tabs.odd.fg = fg
    c.colors.tabs.selected.even.bg = bg_focused
    c.colors.tabs.selected.even.fg = fg_focused
    c.colors.tabs.selected.odd.bg = bg_focused
    c.colors.tabs.selected.odd.fg = fg_focused
  '';

  footTemplate = ''
    [main]
    font=${font}:size=14
    shell=/etc/profiles/per-user/jon/bin/nu
    pad=5x5

    [colors-dark]
    alpha = 0.9
    background = {{colors.surface.default.hex_stripped}}
    foreground = {{colors.on_surface.default.hex_stripped}}
    regular0 = {{colors.surface.default.hex_stripped}}
    regular1 = {{colors.error.default.hex_stripped}}
    regular2 = {{colors.primary.default.hex_stripped}}
    regular3 = {{colors.tertiary.default.hex_stripped}}
    regular4 = {{colors.secondary.default.hex_stripped}}
    regular5 = {{colors.primary_fixed.default.hex_stripped}}
    regular6 = {{colors.secondary_fixed.default.hex_stripped}}
    regular7 = {{colors.on_surface.default.hex_stripped}}

    bright0 = {{colors.outline.default.hex_stripped}}
    bright1 = {{colors.error_container.default.hex_stripped}}
    bright2 = {{colors.primary_container.default.hex_stripped}}
    bright3 = {{colors.tertiary_container.default.hex_stripped}}
    bright4 = {{colors.secondary_container.default.hex_stripped}}
    bright5 = {{colors.inverse_primary.default.hex_stripped}}
    bright6 = {{colors.inverse_surface.default.hex_stripped}}
    bright7 = {{colors.surface_bright.default.hex_stripped}}
  '';

in
{
  imports = [ ];
  accounts.email = {
    maildirBasePath = "${maildir}";
    accounts = {
      gmail = {
        address = "jon.reeve@gmail.com";
        userName = "jon.reeve@gmail.com";
        flavor = "gmail.com";
        passwordCommand = "${pkgs.pass}/bin/pass gmail";
        primary = true;
        mu.enable = true;
        mbsync = {
          enable = true;
          create = "maildir";
          expunge = "both";
          patterns = [ "INBOX" "Lists" "[Gmail]/Sent Mail"];
          extraConfig.channel = {
            MaxMessages = 2000;
            ExpireUnread = "yes";
          };
        };
        realName = "${name}";
        thunderbird.enable = true;
      };
      columbia = {
        address = "jonathan.reeve@columbia.edu";
        userName = "jpr2152@columbia.edu";
        flavor = "gmail.com";
        passwordCommand = "${pkgs.pass}/bin/pass lionmail";
        mu.enable = true;
        mbsync = {
          enable = true;
          create = "maildir";
          expunge = "both";
          patterns = [ "INBOX" "Homework" "Lists" "[Gmail]/Sent Mail"];
          extraConfig.channel = {
            MaxMessages = 2000;
            ExpireUnread = "yes";
          };
        };
        realName = "${name}";
        thunderbird.enable = true;
      };
      protonmail = {
        address = "jonathan@jonreeve.com";
        userName = "jonathan@jonreeve.com";
        passwordCommand = "${pkgs.pass}/bin/pass show 127.0.0.1:1143/jonathan@jonreeve.com";
        imap = {
          host = "127.0.0.1";
          port = 1143;
          tls = {
            enable = true;
            useStartTls = true;
            certificatesFile = "/home/jon/.config/protonmail/bridge/cert.pem";
          };
        };
        smtp = {
          host = "127.0.0.1";
          port = 1025;
          tls = {
            enable = true;
            useStartTls = true;
            certificatesFile = "/home/jon/.config/protonmail/bridge/cert.pem";
          };
        };
        mu.enable = true;
        mbsync = {
          enable = true;
          create = "maildir";
          expunge = "both";
          patterns = [ "INBOX" "Labels/Lists" "Sent" "Drafts" "Spam" ];
          extraConfig.channel = {
            MaxMessages = 2000;
            ExpireUnread = "yes";
          };
        };
        realName = "${name}";
        thunderbird.enable = true;
      };
    };
  };

  gtk = {
    enable = true;
    theme = {
      name = "Adwaita-dark";
      package = pkgs.gnome-themes-extra;
    };
    iconTheme = {
      name = "Flat-Remix-Black-Dark";
      package = pkgs.flat-remix-icon-theme;
    };
  };

  qt = {
    enable = true;
    platformTheme.name = "adwaita";
  };

  fonts.fontconfig = {
    enable = true;
    defaultFonts = {
      emoji = [ "Noto Color Emoji" ];
      monospace = [ font ] ;
      sansSerif = [ "Liberation Sans" ];
      serif = [ "Liberation Serif" ];
    };
  };

  # Dotfiles for the home root, ~/
  home = {
    sessionVariables = {
      DMS_POPOUT_LAYER = "overlay";
      DMS_DANKBAR_LAYER = "top";
    };

    keyboard = {
      options = [ "caps:escape" "esperanto:colemak" ];
      variant = "colemak";
    };
    pointerCursor = {
      package = pkgs.adwaita-icon-theme;
      name = "Adwaita";
      size = 24;
      gtk.enable = true;
      x11.enable = true;
    };

    file = {
      # Vim all the things!
      ".inputrc".text =
        ''
          set editing-mode vi
          set keymap vi-command
        '';
      ".config/matugen/templates/colors-ewal.json.template".text = ewalTemplate;
      ".config/matugen/templates/foot.ini.template".text = footTemplate;      ".config/matugen/templates/qutebrowser-colors.py.template".text = qutebrowserTemplate;
      ".stack/config.yaml".text =
        ''
          templates:
            params:
              author-name: ${name}
              author-email: ${email}
              github-username: ${githubUsername}
        '';
      ".gemini/skills/" = {
        source = ../skills;
        recursive = true;
      };
    };
    stateVersion = "26.05";
  };

  programs = {
    bottom.enable = true;
    broot.enable = true;
    dank-material-shell = {
      enable = true;
      systemd.enable = true;
      enableSystemMonitoring = true;
      enableVPN = true;
      enableDynamicTheming = true;
      enableAudioWavelength = true;
      enableCalendarEvents = true;
      enableClipboardPaste = true;
      managePluginSettings = true;
      settings = {
        runUserMatugenTemplates = true;
        maxWorkspaceIcons = 1;
        showWorkspaceApps = false;
        currentThemeName = "dynamic";
        currentThemeCategory = "dynamic";
        cornerRadius = 11;
        fontFamily = "${font}";
        fontScale = 1.0;
        iconTheme = "Flat-Remix-Black-Dark";
        barConfigs = [
          {
            id = "default";
            name = "Main Bar";
            enabled = true;
            position = 0;
            screenPreferences = [ "all" ];
            showOnLastDisplay = true;
            leftWidgets = [ "launcherButton" "workspaceSwitcher" "focusedWindow" ];
            centerWidgets = [ "music" "plugin:intervalCommand:Org Clock" "clock" "weather" ];
            rightWidgets = [ "systemTray" "clipboard" "cpuUsage" "memUsage" "notificationButton" "battery" "controlCenterButton" ];
            spacing = 0;
            innerPadding = 6;
            bottomGap = 0;
            transparency = 1;
            widgetTransparency = 1;
            squareCorners = true;
            noBackground = false;
            gothCornersEnabled = true;
            gothCornerRadiusOverride = false;
            gothCornerRadiusValue = 15;
            borderEnabled = false;
            borderColor = "surfaceText";
            borderOpacity = 1;
            borderThickness = 1;
            fontScale = 1.0;
            autoHide = false;
            autoHideDelay = 250;
            openOnOverview = false;
            visible = true;
            popupGapsAuto = true;
            popupGapsManual = 4;
            widgetOutlineEnabled = false;
            widgetPadding = 9;
          }
        ];
      };
      plugins = {
        intervalCommand = {
          enable = true;
          settings = {
            variants = [
              {
                id = "Org Clock";
                name = "Org Clock";
                command = "${scripts}/org-clock.nu";
                icon = "clock";
                refreshInterval = 30;
              }
            ];
          };
        };
      };
    };
    dsearch = {
      enable = true;
      config = {
        max_file_bytes = 5242880;  # 5MB
        worker_count = 8;
        
        index_paths = [
          {
            path = "~/Dokumentoj";
            max_depth = 0;  # No limit
            exclude_hidden = false;
            exclude_dirs = [ ".git" ];
          }
          {
            path = "~/Programaroj";
            max_depth = 3;
            exclude_hidden = true;
            exclude_dirs = [ "node_modules" "venv" "target" ".git" "dist" "build" ];
          }
        ];
      };
    };
    direnv = {
      nix-direnv.enable = true;
      enable = true;
      enableZshIntegration = true;
      enableNushellIntegration = true;
    };
    doom-emacs = {
      enable = true;
      doomDir = ./doom;
      emacsPackageOverrides = self: super: {
        citar = super.citar.overrideAttrs (old: {
          src = inputs.citar-src;
        });
      };
      extraBinPackages = with pkgs; [ fd ripgrep git ];
      extraPackages = epkgs: with pkgs; [
        pass gnupg (aspellWithDicts (dicts: with dicts; [ en en-computers en-science eo fr ]))
        ripgrep epkgs.treesit-grammars.with-all-grammars
      ];
    };
    foot = {
      enable = true;
      server.enable = true;
    };
    git = {
      enable = true;
      settings = {
        user = {
          name = "${name}";
          email = "${email}";
        };
        pull.rebase = false;
      };
    };
    gnome-terminal = {
      profile.default = {
        allowBold = false;
        allowBell = false;
        font = "${font}";
        transparencyPercent = 90;
        themeVariant = "dark";
      };
    };
    home-manager.enable = true;
    mbsync.enable = true;
    mu.enable = true;
    neovim = {
      enable = true;
      plugins = with pkgs.vimPlugins; [ ];
      vimAlias = true;
      extraConfig = ''
        set mouse=a
        nnoremap n j
        nnoremap j n
        nnoremap N J
        nnoremap J N
        nnoremap e k
        nnoremap k e
        nnoremap i l
        nnoremap l i
      '';
    };
    nix-index.enable = true;
    nushell = {
      enable = true;
      configFile.source = ./config.nu;
      envFile.source = ./env.nu;
    };
    password-store = {
      enable = true;
      settings = { PASSWORD_STORE_DIR = "${dokumentoj}/Personal/.password-store"; };
    };
    qutebrowser = {
      enable = true;
      extraConfig = ''
        c.statusbar.padding = {'top': 5, 'bottom': 5, 'left': 3, 'right': 3}
        c.tabs.padding = {'top': 2, 'bottom': 2, 'left': 2, 'right': 2}
      '';
      keyBindings = {
        normal = {
          "N" =  "tab-next";
          "E" =  "tab-prev";
          "K" =  "search-prev";
          "l" =  "mode-enter insert";
          "n" =  "scroll down";
          "e" =  "scroll up";
          "i" =  "scroll right";
          "j" =  "search-next";
          "b" =  "set-cmd-text -s :tab-select ";
          "gL" = "open javascript:location.href='org-protocol://capture?template=l&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&body='+encodeURIComponent(document.getSelection())";
          "gM" = "spawn --userscript wikidata-movie";
          "gR" = "open javascript:location.href='org-protocol://roam-ref?template=r&ref='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)";
          "gB" = "spawn -m ${scripts}/downloadBook.py {url}";
          "gV" = "spawn --userscript vulpea-bookmark";
          "gO" = "spawn --userscript org-link";
          "gW" = "spawn --userscript wikidata-movie";
          "pf" = "spawn --userscript qute-pass";
          "gz" = "jseval var d=document,s=d.createElement('script';;s.src='https://www.zotero.org/bookmarklet/loader.js';(d.body?d.body:d.documentElement;.appendChild(s;;void(0;;";
          "gr" = "open javascript:location.href='https://app.raindrop.io/add?link='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&note='+encodeURIComponent((document.getSelection&&document.getSelection().toString())||'')";
          "t" =  "set-cmd-text -s :open -t";
          "Y" =  "yank selection";
          "O" =  "set-cmd-text :open {url:pretty}";
          "<Alt-Left>" =  "back";
          "<Alt-Right>" =  "forward";
        };
      };
      searchEngines = {
        "DEFAULT" =  "https://duckduckgo.com/?q={}";
        "g" =  "https://www.google.com/search?q={}";
        "l" =  "https://www.google.com/search?hl=en&q={}&btnI=I";
        "w" =  "https://en.wikipedia.org/w/index.php?search={}";
        "wd" = "https://www.wikidata.org/w/index.php?search={}";
        "gs" =  "https://scholar.google.com/scholar?q={}";
        "b" =  "https://www.google.com/search?tbm=bks&q={}";
        "aw" =  "https://wiki.archlinux.org/?search={}";
        "o" =  "https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&query={}";
        "p" =  "https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&query={}";
        "d" =  "https://en.wiktionary.org/wiki/{}";
        "v" =  "https://eo.wiktionary.org/wiki/{}";
        "melpa" =  "https://melpa.org/#/?q={}";
        "s" =  "http://stackoverflow.com/search?q={}";
        "ss" = "https://www.semanticscholar.org/search?q={}";
        "m" =  "https://maps.google.com/maps?q={}";
        "c" =  "https://clio.columbia.edu/quicksearch?q={}";
        "gh" =  "https://github.com/search?q={}&type=Repositories";
        "h" =  "https://hackage.haskell.org/packages/search?terms={}";
        "ho" = "https://hoogle.haskell.org/?hoogle={}";
        "libgen" =  "https://libgen.is/search.php?req={}";
        "a" = "https://annas-archive.gl/search?q={}";
        "viki" =  "https://eo.wikipedia.org/w/index.php?search={}";
        "ia" =  "https://archive.org/details/texts?and%5B%5D={}&sin=";
        "mm" =  "https://muse-jhu-edu.ezproxy.cul.columbia.edu/search?action=search&query=content:{}:and&limit=journal_id:131&min=1&max=10&t=search_journal_header";
      };
      settings = {
        content.local_content_can_access_remote_urls = true;
        content.headers.accept_language = "eo,en-US,en,fr";
        fonts = {
          completion.category = "11pt '${font}'";
          default_family = "${font}";
          default_size = "11pt";
          tabs.selected = "11pt '${font}'";
          tabs.unselected = "11pt '${font}'";
        };
        hints.chars = "arstdhneio";
        url.default_page = "${scripts}/homepage/homepage.html";
        colors.webpage.darkmode.enabled = true;
      };
    };
    starship = {
      enable = true;
      enableNushellIntegration = true;
      enableZshIntegration = true;
    };
    thunderbird = {
      enable = true;
      profiles.default.isDefault = true;
    };
    zsh = {
      enable = true;
      enableCompletion = true;
      enableVteIntegration = true;
      autosuggestion.enable = true;
      syntaxHighlighting.enable = true;
    };
    zoxide = {
      enable = true;
      enableNushellIntegration = true;
      enableZshIntegration = true;
    };
  };

  systemd.user = { };

  wayland.windowManager.hyprland = {
    enable = true;
    xwayland.enable = true;
    configType = "hyprlang";
    plugins = [
      (inputs.hyprgrass.packages.${pkgs.system}.default.overrideAttrs (oldAttrs: {
        postPatch = (oldAttrs.postPatch or "") + ''
          sed -i '1s/^/#include <render\/Renderer.hpp>\n/' src/TouchVisualizer.cpp
          substituteInPlace src/TouchVisualizer.cpp \
            --replace-fail "2 * PI" "2 * 3.14159265358979323846" \
            --replace-fail "g_pCompositor->scheduleFrameForMonitor(" "g_pHyprRenderer->damageMonitor("
          substituteInPlace src/GestureManager.cpp \
            --replace-fail "hyprland/src/helpers/Monitor.hpp" "hyprland/src/output/Monitor.hpp" \
            --replace-fail '#include <hyprland/src/output/Monitor.hpp>' '#include <hyprland/src/output/Monitor.hpp>
#include <hyprland/src/state/MonitorState.hpp>' \
            --replace-fail "g_pCompositor->getMonitorFromName(!ev.device->m_boundOutput.empty() ? ev.device->m_boundOutput : \"\")" "State::monitorState()->query().name(!ev.device->m_boundOutput.empty() ? ev.device->m_boundOutput : \"\").run()"
        '';
      }))
    ];
    settings = {
      source = [ "~/.config/hypr/dms/colors.conf" ];
      general = {
        gaps_in = 5;
        gaps_out = 20;
        border_size = 5;
        "col.active_border" = "$primary";
        "col.inactive_border" = "$outline";
        layout = "dwindle";
      };
      scrolling = {
        column_width = 0.5;
        focus_fit_method = 1;
      };
      monitor = ",preferred,auto,1";
      input = {
        kb_layout = "us";
        kb_variant = "colemak";
        kb_options = "caps:escape,esperanto:colemak";
        follow_mouse = 1;
        touchpad = {
          natural_scroll = true;
          tap-to-click = true;
        };
      };
      decoration = {
        rounding = 10;
        blur = {
          enabled = true;
          size = 3;
          passes = 2;
        };
      };
      windowrule = [
        "float on, center on, size 1000 700, match:title ^(vulpea-find)$"
      ];
      debug = {
        vfr = true;
      };
      misc = {
        disable_hyprland_logo = true;
        force_default_wallpaper = 0;
      };
      animations = {
        enabled = true;
        bezier = "myBezier, 0.05, 0.9, 0.1, 1.05";
        animation = [
          "windows, 1, 7, myBezier"
          "windowsOut, 1, 7, default, popin 80%"
          "border, 1, 10, default"
          "borderangle, 1, 8, default"
          "fade, 1, 7, default"
          "workspaces, 1, 6, default, slidevert"
        ];
      };
      workspace = [
        "1, persistent:true"
        "2, persistent:true"
        "3, persistent:true"
        "4, persistent:true"
      ];
      bind = [
        "SUPER,H,exec,footclient"
        "SUPER_SHIFT,C,killactive,"
        "SUPER_SHIFT,Q,exec,dms ipc powermenu open"
        "SUPER_SHIFT,T,togglefloating,"
        "SUPER,space,exec,dms ipc launcher toggle"
        "SUPER,P,pseudo,"
        "SUPER,N,workspace, e+1"
        "SUPER,E,workspace, e-1"
        "SUPER,F,fullscreen, 0"
        "SUPER,T,exec,/home/jon/Agordoj/scripts/hypr.nu float-toggle"
        "SUPER,G,exec,/home/jon/Agordoj/scripts/hypr.nu gaps-toggle"
        "SUPER,S,exec,/home/jon/Agordoj/scripts/hypr.nu layout-toggle"
        "SUPER,W,exec,dms ipc wallpaper set $(find ~/Bildoj/Ekranfonoj -maxdepth 1 -type f | shuf -n 1)"
        "SUPER_SHIFT,W,exec,dms ipc wallpaper set $(find /run/media/jon/systemrestore/.systemrestore/Bildoj -maxdepth 1 -type f | shuf -n 1)"
        "SUPER_SHIFT,E,exec,${emacsclient} -c -a emacs"
        "Alt,H,movefocus,l"
        "Alt,I,movefocus,r"
        "Alt,E,movefocus,u"
        "Alt,N,movefocus,d"
        "SUPER_SHIFT,H,movewindow,l"
        "SUPER_SHIFT,I,movewindow,r"
        "SUPER_SHIFT,E,movewindow,u"
        "SUPER_SHIFT,N,movewindow,d"
        "Alt_Shift,H,movewindoworgroup,l"
        "Alt_Shift,N,movewindoworgroup,d"
        "Alt_Shift,E,movewindoworgroup,u"
        "Alt_Shift,I,movewindoworgroup,r"
        "SUPER,J,workspace,1"
        "SUPER,L,workspace,2"
        "SUPER,U,workspace,3"
        "SUPER,Y,workspace,4"
        "SUPER,5,workspace,5"
        "SUPER,6,workspace,6"
        "SUPER,7,workspace,7"
        "SUPER,8,workspace,8"
        "SUPER,9,workspace,9"
        "SUPER,0,workspace,10"
        "SUPER_SHIFT,J,movetoworkspace,1"
        "SUPER_SHIFT,L,movetoworkspace,2"
        "SUPER_SHIFT,U,movetoworkspace,3"
        "SUPER_SHIFT,Y,movetoworkspace,4"
        "ALT,5,movetoworkspace,5"
        "ALT,6,movetoworkspace,6"
        "ALT,7,movetoworkspace,7"
        "ALT,8,movetoworkspace,8"
        "ALT,9,movetoworkspace,9"
        "ALT,0,movetoworkspace,10"
        ",XF86AudioRaiseVolume,exec,dms ipc call audio increment 5"
        ",XF86AudioLowerVolume,exec,dms ipc call audio decrement 5"
        ",XF86AudioMute,exec,dms ipc call audio mute"
        ",XF86AudioPlay,exec,dms ipc call mpris playPause"
        ",XF86AudioPrev,exec,dms ipc call mpris previous"
        ",XF86AudioNext,exec,dms ipc call mpris next"
        ",XF86MonBrightnessUp,exec,dms ipc call brightness increment 10 backlight:intel_backlight"
        ",XF86MonBrightnessDown,exec,dms ipc call brightness decrement 10 backlight:intel_backlight"
        ",Print,exec,${emacsclient} -c -F '((name . \"vulpea-find\"))' --eval '(consult-vulpea-find)'"
        "SUPER_SHIFT,V,exec,python3 ${scripts}/visualize_habits.py && qutebrowser journal_stats.html habit_heatmap.html"
      ];
      bindm = [
        "SUPER, mouse:272, movewindow"
        "SUPER, mouse:273, resizewindow"
      ];
      exec-once = [
        "megasync"
        "${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1"
        "iio-hyprland"
      ];
      gestures = {
        workspace_swipe_touch = false; # Set to false to allow hyprgrass to work
        gesture = [
          "3, vertical, workspace"
          "3, left, dispatcher, layoutmsg, move +col"
          "3, right, dispatcher, layoutmsg, move -col"
        ];
      };
      plugin = {
        touch_gestures = {
          # The number of fingers for a workspace swipe
          workspace_swipe_fingers = 3;
          sensitivity = 4.0;
          experimental = {
            send_cancel = true;
          };

          # Use both bind and gesture for maximum compatibility
          hyprgrass-bind = [
            ", swipe:3:u, workspace, e-1"
            ", swipe:3:d, workspace, e+1"
            ", swipe:3:l, layoutmsg, move +col"
            ", swipe:3:r, layoutmsg, move -col"
            ", edge:d:u, exec, dms ipc launcher toggle"
          ];
          hyprgrass-gesture = [
            "swipe, 3, vertical, workspace"
            "swipe, 3, left, dispatcher, layoutmsg, move +col"
            "swipe, 3, right, dispatcher, layoutmsg, move -col"
          ];
        };
      };
    };
  };

  xdg = {
    enable = true;
    configFile = {
      "matugen/config.toml".text = ''
        [config]

        [templates.ewal]
        input_path = '/home/jon/.config/matugen/templates/colors-ewal.json.template'
        output_path = '/home/jon/.cache/wal/colors.json'
        post_hook = "${scripts}/theme-reload.nu --emacsclient ${emacsclient}"

        [templates.foot]
        input_path = '/home/jon/.config/matugen/templates/foot.ini.template'
        output_path = '/home/jon/.config/foot/foot.ini'

        [templates.qutebrowser]
        input_path = '/home/jon/.config/matugen/templates/qutebrowser-colors.py.template'
        output_path = '/home/jon/.cache/dms-qute-config.py'
        post_hook = "${scripts}/theme-reload.nu --qutebrowser ${qutebrowser}"
      '';
    };
    dataFile = {
      "qutebrowser/userscripts/" = {
        source = ../scripts/qutebrowser-userscripts;
        recursive = true;
      };
    };
    mimeApps = {
      enable = true;
      defaultApplications = {
        "application/pdf" = "org.gnome.Evince.desktop";
        "text/html" = "org.qutebrowser.qutebrowser.desktop";
        "x-scheme-handler/org-protocol" = "org-protocol.desktop";
        "x-scheme-handler/http" = "org.qutebrowser.qutebrowser.desktop";
        "x-scheme-handler/https" = "org.qutebrowser.qutebrowser.desktop";
        "x-scheme-handler/about" = "org.qutebrowser.qutebrowser.desktop";
        "x-scheme-handler/unknown" = "org.qutebrowser.qutebrowser.desktop";
      };
    };
  };
}
