#!/bin/zsh

TODOFILE=~/Dropbox/Personal/Todo/todo.txt
DONEFILE=~/Dropbox/Personal/Todo/done.txt

# This gets a numeric day of the week. Monday is 1. 
DAYOFWEEK=`date +%u`

for i in `seq $DAYOFWEEK`
do
	let j=i-1 # adjust for today
	EXPR=`date +%Y-%m-%d -d "$j days ago"`
	DONE1=$(grep -c "x $EXPR" $TODOFILE)
	DONE2=$(grep -c "x $EXPR" $DONEFILE)
	DONETODAY=`echo "$DONE1+$DONE2" | bc`
	let DONETHISWEEK=DONETHISWEEK+DONETODAY
done
echo $DONETHISWEEK
