#!/bin/bash
STATUS=$(dropbox-cli status)

case $STATUS in 
	'Up to date')
		SYMBOL=✓
		;;
	"Uploading")
		SYMBOL=↑
		;;
	"Syncing")
		SYMBOL=S
		;;
	"Dropbox isn't running!")
		SYMBOL=x
		;;
	"Indexing...")
		SYMBOL=..
		;;
esac

echo $SYMBOL

if [[ $STATUS == ✓ ]]; then
    echo "#00FF00"
else
    echo "#FF0000"
fi
